server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

outbound:
  identity:
    client-id: ""
    client-secret: ""
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "dYPpI+h479I36G4z97u/MMIzST9Sb4QZF7/6k8aXVbKKbcz6BOGaJPbXxx8bBjL4"
  valid-duration: 200 #in second
  refreshable-duration: 200 #in second
app:
  default-user:
    username: "admin"
    password: "admin"

  default-roles:
    admin: "ADMIN"
    user: "USER"

  services:
    profile: http://localhost:8081/profile
