server:
  port: 8085
  servlet:
    context-path: /chat

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
app:
  services:
    oto: http://localhost:8080/identity
    profile:
      url: http://localhost:8081