version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: identity_service
      MYSQL_USER: quyen
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  oto:
    build: ./oto
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/identity_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: quyen
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"

  profile-service:
    build: ./profile-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/identity_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: quyen
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8081:8081"

  post-service:
    build: ./post-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/identity_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: quyen
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8083:8083"

  chat-service:
    build: ./chat-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/identity_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: quyen
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8085:8085"

  file-service:
    build: ./file-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/identity_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: quyen
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8084:8084"

  api-gateway:
    build: ./api-gateway
    depends_on:
      - oto
      - profile-service
      - post-service
      - chat-service
      - file-service
    ports:
      - "8888:8888"

volumes:
  mysql_data:
